spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-sprint-2
    username: postgres
    password: eldos

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 7777
